Repository Echtzeitsysteme/gips, pull requests merged in 2025-05, with the labels that each got.

#258 Disableable GIPSL->Intermediate trace in Eclipse preference page
  org.emoflon.gips.build/src/org/emoflon/gips/build/GipsBuilderUtils.java
  org.emoflon.gips.build/src/org/emoflon/gips/build/transformation/GipsToIntermediate.java
  org.emoflon.gips.build/src/org/emoflon/gips/build/transformation/GipsTracer.java
  org.emoflon.gips.eclipse/src/org/emoflon/gips/eclipse/api/ITraceManager.java
  org.emoflon.gips.eclipse/src/org/emoflon/gips/eclipse/pref/PluginPreferenceInitializer.java
  org.emoflon.gips.eclipse/src/org/emoflon/gips/eclipse/pref/PluginPreferencePage.java
  org.emoflon.gips.eclipse/src/org/emoflon/gips/eclipse/pref/PluginPreferences.java
  org.emoflon.gips.eclipse/src/org/emoflon/gips/eclipse/service/ContextManager.java
Labels: enhancement

#259 CPLEX LP without declarations
  org.emoflon.gips.eclipse.cplexlp.ui/src/org/emoflon/gips/eclipse/ui/labeling/CplexLpLabelProvider.java
  org.emoflon.gips.eclipse.cplexlp/META-INF/MANIFEST.MF
  org.emoflon.gips.eclipse.cplexlp/model/generated/CplexLp.ecore
  org.emoflon.gips.eclipse.cplexlp/model/generated/CplexLp.genmodel
  org.emoflon.gips.eclipse.cplexlp/src/org/emoflon/gips/eclipse/CplexLp.xtext
  org.emoflon.gips.eclipse.cplexlp/src/org/emoflon/gips/eclipse/CplexLpRuntimeModule.java
  org.emoflon.gips.eclipse.cplexlp/src/org/emoflon/gips/eclipse/linker/CplexLpLinker.java
  org.emoflon.gips.eclipse.cplexlp/src/org/emoflon/gips/eclipse/scoping/CplexLpScopeProvider.java
  org.emoflon.gips.eclipse.cplexlp/src/org/emoflon/gips/eclipse/scoping/CplexQualifiedNameProvider.java
  org.emoflon.gips.eclipse.cplexlp/src/org/emoflon/gips/eclipse/scoping/DynamicVariableDeclarationLocator.java
  org.emoflon.gips.eclipse.cplexlp/src/org/emoflon/gips/eclipse/state/DynamicVariableDeclarationComputer.java
  org.emoflon.gips.eclipse.cplexlp/src/org/emoflon/gips/eclipse/validation/CplexLpValidator.java
  org.emoflon.gips.eclipse/src/org/emoflon/gips/eclipse/codemining/VariableValueCodeMiningProvider.java
  org.emoflon.gips.eclipse/src/org/emoflon/gips/eclipse/connector/CplexLpEditorTraceConnectionFactory.java
  org.emoflon.gips.eclipse/src/org/emoflon/gips/eclipse/connector/highlight/CplexAnnotationHighlightStrategy.java
  org.emoflon.gips.eclipse/src/org/emoflon/gips/eclipse/connector/highlight/CplexLpMarkerHighlightStrategy.java
Labels: enhancement

#263 Fixes some typos in README.md
  README.md
Labels: bug, documentation

#268 Fixes a copy paste error within the `flipOperator(...)` method
  org.emoflon.gips.build/src/org/emoflon/gips/build/transformation/helper/GipsTransformationUtils.java
Labels: bug
